name: Intializing Database

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  init-db:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ysanskarr7/Banking-app-2-tier
          ref: main

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::972293797085:role/github-deploy-policy
          aws-region: us-west-1

      - name: Upload file on S3
        run: |
          aws s3 mb s3://972293797085-devops-scripts --region us-west-1 2>/dev/null || true
          aws s3 cp init.sql s3://972293797085-devops-scripts/init.sql --region us-west-1
          aws s3 cp init.py s3://972293797085-devops-scripts/init.py --region us-west-1
          echo "✅ Files Uploaded to bucket.."

      - name: Initializing Database on RDS using Ec2
        id: init
        run: |
          CMD_ID=$(aws ssm send-command \
            --targets "Key=tag:App,Values=flask" \
            --document-name "AWS-RunShellScript" \
            --parameters '{"commands":[
              "aws s3 cp s3://972293797085-devops-scripts/init.py /tmp/init.py",
              "aws s3 cp s3://972293797085-devops-scripts/init.sql /tmp/init.sql",
              "python3 /tmp/init.py || exit 1",
              "rm /tmp/init.py"
            ]}' \
            --query 'Command.CommandId' \
            --output text \
            --region us-west-1)
          echo "cmd_id=$CMD_ID" >> $GITHUB_OUTPUT

      - name: Show Results
        run: |
          sleep 30

          aws ssm list-command-invocations \
            --command-id "${{ steps.init.outputs.cmd_id }}" \
            --details \
            --region us-west-1 \
            --output text

          FAILED=$(aws ssm list-command-invocations \
            --command-id "${{ steps.init.outputs.cmd_id }}" \
            --query "length(CommandInvocations[?Status=='Failed'])" \
            --output text \
            --region us-west-1)

          [ "$FAILED" -gt 0 ] && \
            echo "::error::Database Creation Failed $FAILED instance(s)!" && \
            exit 1

          echo "✅ Database Created Successfully"