name: Intializing Database

on:
  workflow_dispatch

permissions:
  id-token: write
  contents: read

jobs:
  init-db:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ysanskarr7/Banking-app-2-tier
          ref: main

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::972293797085:role/github-deploy-policy
          aws-region: us-west-1

      - name: Upload file on S3
        run: |
          aws s3 mb s3://972293797085-devops-scripts --region us-west-1 2>/dev/null || true
          aws s3 cp init.sql s3://972293797085-devops-scripts/init.sql 
          aws s3 cp init.py s3://972293797085-devops-scripts/init.py
          echo "✅ Files Uploaded to bucket.."