name : Smoke Testing For Infra and Networking

on:
   workflow_call:

jobs:
  working-job:
    runs-on: ubuntu-latest

    steps:
      - name : Echo Message
        run : echo "Smoke Testing For Infra and Networking Runs successfully ✅"