name : Test Connection For Pipelines

on:
   workflow_call:

jobs:
  working-job:
    runs-on: ubuntu-latest

    steps:
      - name : Echo Message
        run : echo "Github Action is working successfully ✅"