name: Test Fleet health and Env Variables

on:
  workflow_call:


permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::972293797085:role/github-deploy-policy
          aws-region: us-west-1

      - name: Print private IPs
        run: |
          CMD_ID=$(aws ssm send-command \
            --targets "Key=tag:App,Values=flask" \
            --document-name "AWS-RunShellScript" \
            --parameters '{"commands":["hostname -I"]}' \
            --query 'Command.CommandId' --output text)

          sleep 15

          aws ssm list-command-invocations \
            --command-id "$CMD_ID" --details \
            --query "CommandInvocations[*].{Instance:InstanceId,IP:CommandPlugins[0].Output}" \
            --output table