name: Test Fleet health and Env Variables

on:
  workflow_dispatch:


permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::972293797085:role/github-deploy-policy
          aws-region: us-west-1

      - name: Fleet Health Checks
        id: health
        run: |
          CMD_ID=$(aws ssm send-command \
            --targets "Key=tag:App,Values=flask" \
            --document-name "AWS-RunShellScript" \
            --parameters '{"commands":[
              "hostname -I",
              "docker --version 2>/dev/null || echo DOCKER NOT INSTALLED",
              "aws --version 2>/dev/null || echo AWS CLI NOT INSTALLED",
              "mysql --version 2>/dev/null || echo MYSQL NOT INSTALLED",
              "aws ssm get-parameters-by-path --path /application/banking --with-decryption --region us-west-1 | grep -E Name"
              ]}' \
            --query 'Command.CommandId' \
            --output text \
            --region us-west-1
            )
          echo "cmd_id=$CMD_ID" >> $GITHUB_OUTPUT
      
      
      - name: Show Results
        run: |  
          sleep 20
          aws ssm list-command-invocations \
            --command-id "${{ steps.health.outputs.cmd_id }}" \
            --details \
            --region us-west-1 \
            --output text 
          
          FAILED=$(aws ssm list-command-invocations \
            --command-id "${{ steps.health.outputs.cmd_id }}" \
            --query "length(CommandInvocations[?Status=='Failed'])" \
            --output text \
            --region us-west-1
            )

          [ "$FAILED" -gt 0 ] && \
          echo "::error::Health Check Failed on $FAILED instances" && \
          exit 1

          echo "ALL Instances Healthy ✅"